"""
Graph 1 — Sourcing Pipeline
============================
Entry point: triggered by POST /api/jobs (via BackgroundTask in job_controller.py).

Flow:
    sourcing_hunter (A1)
          │
    score_sources (A5)       ← compute source fit for all sourced candidates
          │
         END

Outreach emails are NOT sent automatically.  The manager reviews sourced
candidates in the portal and sends invites individually via:
    POST /api/jobs/{job_id}/candidates/{candidate_id}/send-invite

OA is generated by A2 only after a candidate submits their application
via the public portal (POST /api/jobs/{job_id}/apply).

State: SourcingState
Fallback: _FallbackGraph1 runs the same sequence without LangGraph if the
          library is unavailable.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any

try:
    from langgraph.graph import END, StateGraph
    _LANGGRAPH_AVAILABLE = True
except ImportError:
    END = "__END__"
    StateGraph = None
    _LANGGRAPH_AVAILABLE = False

from app.agents.agent1.sourcing_hunter import run_sourcing_hunter
from app.agents.agent5 import compute_source_scores
from app.models.states import SourcingState
from app.services.firestore_service import update_job

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# Graph nodes
# ══════════════════════════════════════════════════════════════════════════════

async def _node_sourcing_hunter(state: SourcingState) -> SourcingState:
    logger.info("[Graph1] node: sourcing_hunter | job=%s", state["job_id"])
    state = await run_sourcing_hunter(state)
    return state


async def _node_score_sources(state: SourcingState) -> SourcingState:
    logger.info("[Graph1] node: score_sources | job=%s", state["job_id"])
    # compute_source_scores and update_job are synchronous Firestore ops — run in thread
    result = await asyncio.to_thread(compute_source_scores, state)
    state  = result if result is not None else state
    await asyncio.to_thread(update_job, state["job_id"], {"status": "SOURCED"})
    return {**state, "graph1_complete": True}


# ══════════════════════════════════════════════════════════════════════════════
# Fallback runner (no LangGraph)
# ══════════════════════════════════════════════════════════════════════════════

class _FallbackGraph1:
    async def ainvoke(self, state: SourcingState) -> SourcingState:
        state = await _node_sourcing_hunter(state)
        state = await _node_score_sources(state)
        return state


# ══════════════════════════════════════════════════════════════════════════════
# Graph builder
# ══════════════════════════════════════════════════════════════════════════════

def build_graph1() -> Any:
    if not _LANGGRAPH_AVAILABLE or StateGraph is None:
        logger.info("[Graph1] LangGraph unavailable — using fallback runner")
        return _FallbackGraph1()

    graph = StateGraph(SourcingState)

    graph.add_node("sourcing_hunter", _node_sourcing_hunter)
    graph.add_node("score_sources",   _node_score_sources)

    graph.set_entry_point("sourcing_hunter")
    graph.add_edge("sourcing_hunter", "score_sources")
    graph.add_edge("score_sources",   END)

    return graph.compile()


# ══════════════════════════════════════════════════════════════════════════════
# Public runner
# ══════════════════════════════════════════════════════════════════════════════

async def run_sourcing_pipeline(
    job_id: str,
    jd_text: str,
    locations: list[str],
    experience_min: int,
    experience_max: int,
) -> SourcingState:
    """
    Entry point for the sourcing pipeline.
    Called from job_controller via BackgroundTask.
    """
    initial_state: SourcingState = {
        "job_id":             job_id,
        "jd_text":            jd_text,
        "tech_stack":         [],
        "experience_range":   (experience_min, experience_max),
        "locations":          locations,
        "sourced_candidates": [],
        "outreach_sent":      False,
        "graph1_complete":    False,
    }

    pipeline = build_graph1()
    final    = await pipeline.ainvoke(initial_state)
    logger.info("[Graph1] pipeline done | job=%s | complete=%s", job_id, final.get("graph1_complete"))
    return final
